apiVersion: v1
kind: PersistentVolume
metadata:
  name: story-pv-volume
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data"
    type: DirectoryOrCreate