apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: story-pvc
spec: 
  volumeName: story-pv-volume
  storageClassName: standard
  accessModes: 
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi